# Generated by Django 3.0.5 on 2020-04-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200426_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_score',
        ),
    ]
