# Generated by Django 3.0.5 on 2020-04-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
